Already on 'addinggriffin'
wandb: Currently logged in as: stevenzhou0816100. Use `wandb login --relogin` to force relogin
The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:54<01:48, 54.31s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:52, 56.31s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:52, 56.32s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:52, 56.35s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:57<01:54, 57.45s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:52, 56.34s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:52, 56.39s/it]Loading checkpoint shards:  33%|███▎      | 1/3 [00:56<01:53, 56.55s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:50<00:55, 55.44s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.05s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:53<00:56, 56.48s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.02s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.03s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.13s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.04s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [01:52<00:56, 56.05s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:19<00:00, 43.55s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:19<00:00, 46.65s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 43.58s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 46.97s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 43.58s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 43.59s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:21<00:00, 43.63s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 46.98s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 46.98s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [02:21<00:00, 47.05s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 43.58s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:20<00:00, 46.97s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [02:22<00:00, 43.84s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:22<00:00, 47.35s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Loading checkpoint shards: 100%|██████████| 3/3 [02:21<00:00, 43.61s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:21<00:00, 47.01s/it]
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/CommonSenseReasoning/mainfordebugging.py", line 111, in <module>
    model = get_llama_griffin_no_tree(model, schedule_k, patternstrict = args.patternstrict) 
TypeError: get_llama_griffin_no_tree() got an unexpected keyword argument 'patternstrict'
[2024-07-13 02:08:06,595] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 155022 closing signal SIGTERM
[2024-07-13 02:08:07,010] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 155017) of binary: /fsx-storygen/beidic/anaconda3/envs/griffin/bin/python3.9
Traceback (most recent call last):
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/fsx-storygen/beidic/anaconda3/envs/griffin/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
mainfordebugging.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 155018)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 155019)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 155020)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 155021)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 155023)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 155024)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-13_02:08:06
  host      : a100-st-p4de24xlarge-171.fair-a100.hpcaas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 155017)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
